# config/sensitive_keywords.yaml
intimacy:
  - kiss
  - hug
  - cuddle
  - bare shoulder
  - cleavage
religion:
  - hijab
  - mosque
  - church
  - cross
  - bible
violence:
  - gun
  - blood
  - weapon
  - knife
nudity:
  - nude
  - topless
  - lingerie
  - erotic
politics:
  - flag
  - protest
  - president
  - election
